# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio

variables:
  Solution: '**/*.sln'
  Platform: 'Any CPU'
  Configuration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- task: VSBuild@1
  inputs:
    solution: '$(Solution)'
    platform: '$(Platform)'
    configuration: '$(Configuration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SysBot-ACNH'
  inputs:
    PathtoPublish: 'CrossBot.ConsoleApp\bin\Release\net47'
    ArtifactName: SysBot-ACNH
  condition: succeededOrFailed()